#!/bin/bash
NAME="whatsapp-bot-api"
VIRTUALENV="/home/ubuntu/whatsapp-bot-api/env_whatsapp-bot-api/"
DIR="/home/ubuntu/whatsapp-bot-api/"
USER=root
GROUP=sudo
TIMEOUT=99999
echo "Starting $NAME as `whoami`"
cd $VIRTUALENV
source bin/activate
cd $DIR
pip install -r requirements.txt
exec gunicorn app:app \
--timeout $TIMEOUT \
--user=$USER --group=$GROUP \
--log-level=debug \
--bind=0.0.0.0:8080
